name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/api-center
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            deactivate
            sudo find /opt/api-center/odoo_woocommerce_sync -name "*.pyc" -delete
            sudo -u odoo odoo --config /etc/odoo/odoo.conf -u odoo_woocommerce_sync --stop-after-init
            sudo systemctl restart odoo